name: build

on:
  workflow_dispatch:

jobs:
  check_format:
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Check format
        env:
          MAVEN_OPTS: "-DskipTests=true -Dmaven.javadoc.skip=true"
        run: mvn clean install -B -V && sh ./tools/check_format.sh
    strategy:
      matrix:
        os: &id001
          - ubuntu-latest
          - windows-latest
          - macos-latest
      fail-fast: false
  test_jraft_core:
    needs: check_format
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Maven Test
        env:
          MAVEN_OPTS: "-DskipTests=true -Dmaven.javadoc.skip=true"
        run: mvn clean install -B -V && (mvn --projects jraft-core test ||
          mvn --projects jraft-core test || mvn --projects jraft-core test)
    strategy:
      matrix:
        os: *id001
      fail-fast: false
  test_rheakv_core:
    needs: check_format
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Maven Test
        env:
          MAVEN_OPTS: "-DskipTests=true -Dmaven.javadoc.skip=true"
        run: mvn clean install -B -V && (mvn --projects
          jraft-rheakv/rheakv-core test || mvn --projects jraft-rheakv/rheakv-core test || mvn --projects
          jraft-rheakv/rheakv-core test)
    strategy:
      matrix:
        os: *id001
      fail-fast: false
  test_rheakv_pd:
    needs: check_format
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Maven Test
        env:
          MAVEN_OPTS: "-DskipTests=true -Dmaven.javadoc.skip=true"
        run: mvn clean install -B -V && (mvn --projects
          jraft-rheakv/rheakv-pd test || mvn --projects jraft-rheakv/rheakv-pd test || mvn --projects
          jraft-rheakv/rheakv-pd test)
    strategy:
      matrix:
        os: *id001
      fail-fast: false
  test_rpc_grpc_impl:
    needs: check_format
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Maven Test
        env:
          MAVEN_OPTS: "-DskipTests=true -Dmaven.javadoc.skip=true"
        run: mvn clean install -B -V && (mvn --projects
          jraft-extension/rpc-grpc-impl test || mvn --projects jraft-extension/rpc-grpc-impl test || mvn --projects
          jraft-extension/rpc-grpc-impl test)
    strategy:
      matrix:
        os: *id001
      fail-fast: false
